OPENAI_API_KEY: AIzaSyCYkivW_PQEE3ayBSYTXw1mtnQiDMau7GM
history_file: chat_history.json
model: "qwen/qwen3-coder:free"
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Riko.
      You speak like a snarky anime girl.
      Always refer to the user as "Xasanboy".

sovits_ping_config:
  text_lang: en
  prompt_lang : en
  ref_audio_path : /samples/main_sample.wav
  prompt_text :  This is a sample voice for you to just get started with because it sounds kind of cute but just make sure this doesn't have long silences.
  # ブレタブレのヤブ医者が タケヤブの中へスッタコラサ ヤブからボーンにス
  # お買い物、お買い物、な、なに? 90円で買ったネギだし、まあいいか。
  # 비가 내리고, 부둥이 들어갑니다. 부릉부릉, 찌르르. 무거워집니다. 달콤해집니다.
